network:
  PRETRAINED: 1

train:
  LR: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  BATCH_SIZE: 128
  GAMMA: 0.5
  mnist:
    N_EPOCHS: 5
    MILE_STONE: [3]
    T_max: 200
  cifar10:
    N_EPOCHS: 200
    MILE_STONE: [20, 40]
    T_MAX: 200

attack: 
  TROJ_FRACTION: 0.2
  SOURCE_TARGET_PAIR: {0:1}

misc:
  VERBOSE: 1
  MONITOR_WINDOW: 5
